# gz_bridge.yaml
- ros_topic_name: "/robot/end_effector/force_torque"
  gz_topic_name: "/arm/wrench"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
